name: .NET CD

on:
  push:
    branches: [ main, 'release/*' ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref == 'refs/heads/main' && 'production' || 'staging' }}

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish --configuration Release --output ./publish --no-build

    # Deployment per ambiente di staging (branch release/*)
    - name: Deploy to Staging
      if: startsWith(github.ref, 'refs/heads/release/')
      run: |
        echo "Deploying to staging environment..."
        # Qui inserisci i comandi per il deploy su staging
        # Ad esempio usando Azure CLI:
        # az webapp deployment source config-zip --resource-group myResourceGroup --name myStagingApp --src ./publish/publish.zip

    # Deployment per ambiente di produzione (branch main)
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: |
        echo "Deploying to production environment..."
        # Qui inserisci i comandi per il deploy su produzione
        # Ad esempio usando Azure CLI:
        # az webapp deployment source config-zip --resource-group myResourceGroup --name myProductionApp --src ./publish/publish.zip