name: Verify HealthChecks

on:
  push:
    branches: [ main, develop, 'release/*' ]
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours

jobs:
  verify-healthchecks:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '7.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Start Application
      run: |
        dotnet run --project ./src/HealthCheckDemo/HealthCheckDemo.csproj --no-build --configuration Release &
        echo "Waiting for application to start..."
        sleep 10

    - name: Check Health Endpoint
      run: |
        HEALTH_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/health)
        if [ "$HEALTH_STATUS" -ne 200 ]; then
          echo "Health check failed with status: $HEALTH_STATUS"
          exit 1
        fi
        echo "Health check passed with status: $HEALTH_STATUS"

    - name: Check Health UI
      run: |
        UI_STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:5000/healthchecks-ui)
        if [ "$UI_STATUS" -ne 200 ]; then
          echo "HealthChecks UI not available, status: $UI_STATUS"
          exit 1
        fi
        echo "HealthChecks UI available, status: $UI_STATUS"